### PR TITLE
Fix multiple mistakes

### PR DESCRIPTION
**Pull request by tom-reinders**
# Pull Request Overview

Fixes multiple mistakes

## Changes Introduced

List specific changes made (e.g., added new or refactored existing syntax).
Include reasons for complex or significant changes

## Linked Issue(s)

- [ ] Link to the issue ticket(s) this PR addresses (e.g., `Fixes #123`)

## Additional Notes

- [ ] Add any other context or notes about the pull request here (optional)

### CODE REVIEW

**Comment by tom-reinders** [comment]
@lifeparticle What is the preferred way/location to save images?

**Comment by lifeparticle** [comment]
@tom-reinders Thank you for your contribution. You can drag and drop the image into the markdown file.

**Comment by lifeparticle** [comment]
@tom-reinders Hi, please let me know if you have any questions. Thanks you.

**Comment by lifeparticle** [comment]
LGTM, many thanks @tom-reinders

**Pull request merged**
